#!/bin/sh

DEBUG=true
NOTICE=true
WARN=true
ERR=true

debug() {
        if [ $DEBUG ]; then
                logger -t ${logger_tag} -p user.debug $@
        fi
}

notice() {
        if [ $NOTICE ]; then
                logger -t ${logger_tag} -p user.notice $@
        fi
}

warn() {
        if [ $WARN ]; then
                logger -t ${logger_tag} -p user.warn $@
        fi
}

err() {
        if [ $ERR ]; then
                logger -t ${logger_tag} -p user.err $@
        fi
}

# logger tag
logger_tag=$0

start() {
	if [ -x /opt/bin/sysconfig/sysconfig.lua ]; then
		notice "ready to execute /opt/bin/sysconfig/sysconfig.lua"
		cd /opt/bin/sysconfig
		./sysconfig.lua -s 50 0 250
    fi
}

case "$1" in
	start)
		"$1"
		;;
	stop)
		;;
	restart|reload)
		;;
esac
