#!/bin/sh
# copy sw-versions to /etc/ directory

DEBUG=true
NOTICE=true
WARN=true
ERR=true

debug() {
        if [ $DEBUG ]; then
                logger -t ${logger_tag} -p user.debug $@
        fi
}

notice() {
        if [ $NOTICE ]; then
                logger -t ${logger_tag} -p user.notice $@
        fi
}

warn() {
        if [ $WARN ]; then
                logger -t ${logger_tag} -p user.warn $@
        fi
}

err() {
        if [ $ERR ]; then
                logger -t ${logger_tag} -p user.err $@
        fi
}

# logger tag
logger_tag=$0

start() {
	notice "prepare to copy sw-versions issue"
	/bin/cp -p /boot/sw-versions /tmp/sw-versions
	/bin/cp -p /boot/issue /tmp/issue
}

stop() {
	/bin/rm -rf /tmp/sw-versions
	/bin/rm -rf /tmp/issue
}

case "$1" in
        start|stop|restart)
                "$1";;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac

